### DISCUSSION TITLE
skmel133 data (Cell Systems paper) training

### DISCUSSION THREAD

**Discussion by judyueshen** [jiweiqi/CellBox.jl#19] [Show and tell]
Default training parameters and training scheme

```yaml
data: "data/skmel133_24"
ns: 24
alpha: 1.0
tfinal: 20.0
ntotal: 1
nplot: 100
batch_size: 1
epoch_size: -1

lr: 1.e-4
weight_decay: 1.e-6

n_mu: 2

n_exp_train: 69
n_exp_val: 10
n_exp_test: 10
noise: 0.01

n_iter_max: 10000
n_plot: 20 # frequency of callback

n_iter_buffer: 50
n_iter_burnin: 100
n_iter_tol: 100
convergence_tol: 1e-8
```
![loss_grad](https://user-images.githubusercontent.com/25517964/113742742-ec7e5b80-96d0-11eb-8672-4701a15245ab.png)
*No ground truth parameter (alpha/w)

Scatter plot for all conditions combined, same as fig2 of Cell Systems paper. 
![predicted_response_correlation_with_real_data](https://user-images.githubusercontent.com/25517964/113742763-f0aa7900-96d0-11eb-8a32-0067ca39878f.png)
